x-vpn-config:
  client_config: &client_config
    restart: unless-stopped
    network_mode: host
    ipc: host
    configs: [ dds-config.client.xml ]
    env_file: dds/client.env

configs:
  dds-config.client.xml:
    file: ./dds/config.client.xml

# ============================================================ #

services:

  rviz:
    <<: *client_config
    image: husarion/rviz2:humble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1



