x-dds-configs:
  - &client_config { network_mode: host, ipc: host, configs: [ client.xml ], env_file: dds/client.env }
  - &server_config { network_mode: host, ipc: host, configs: [ server.xml ], env_file: dds/server.env }
  - &simple_config { network_mode: host, ipc: host, configs: [ simple.xml ], env_file: dds/simple.env }

configs: 
  client.xml: { file: dds/client.xml }
  server.xml: { file: dds/server.xml }
  simple.xml: { file: dds/simple.xml }

# ============================================================ #

services:

  mapping:
    <<: *client_config
    image: husarion/slam-toolbox:humble
    container_name: slam-toolbox
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  navigation:
    <<: *client_config
    image: husarion/navigation2:humble
    volumes:
      - ./config/nav2_params_pure_pursuit.yaml:/nav2_params.yaml
    command: >
      ros2 launch nav2_bringup navigation_launch.py
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  rviz:
    <<: *client_config
    image: husarion/rviz2:humble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
